version: 2
jobs:
   build:
     docker:
       - image: circleci/python:3.6
     steps:
       - checkout
       - run: echo "hello world"

dependencies:
  pre:
    - sudo pip install awsebcli

deployment:
  production:
    branch: master
    commands:
      - bash ./setup-eb.sh
      - eb deploy



